export const ADD_INGRIDENT="ADD_INGRIDENT"
export const REMOVE_INGRIDENT="REMOVE_INGRIDENT"
export const UPDATE_PURCHAGEABLE="UPDATE_PURCHAGEABLE"

export const RESET_INGREDIENT="RESET_INGREDIENT"

export const LOAD_ORDERS="LOAD_ORDERS"
export const ORDER_LOAD_FAILED="ORDER_LOAD_FAILED"

export const AUTH_SUCCESS="AUTH_SUCCESS"
export const AUTH_LOGOUT="AUTH_LOGOUT"
export const AUTH_LOADING="AUTH_LOADING"
